---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: eyJhdXRocyI6eyIxMC4xMzguMC4yOjUwMDAiOnsicGFzc3dvcmQiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4ifX19
