---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"10.138.0.2:5000":{"password":"admin","username":"admin"}}}'
