---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: basic-sc
spec:
  gitImplementation: libgit2
  ignore: ""
  interval: 1m0s
  ref:
    branch: main
  timeout: 20s
  url: https://github.com/kontinue/hello-world
status:
  artifact:
    checksum: f8fe9fda3699fc45a2d4a54800a58fee7e380c67
    lastUpdateTime: "2022-02-10T23:31:01Z"
    path: gitrepository/default/hello/af9d9e843543fa20ac59019d20e685375c687093.tar.gz
    revision: main/af9d9e843543fa20ac59019d20e685375c687093
    url: http://source-controller.gitops-toolkit.svc.cluster.local./gitrepository/default/hello/af9d9e843543fa20ac59019d20e685375c687093.tar.gz
  conditions:
    - lastTransitionTime: "2022-02-10T23:31:01Z"
      message: 'Fetched revision: main/af9d9e843543fa20ac59019d20e685375c687093'
      reason: GitOperationSucceed
      status: "True"
      type: Ready
  observedGeneration: 1
  url: http://source-controller.gitops-toolkit.svc.cluster.local./gitrepository/default/hello/latest.tar.gz

---
apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: basic-sc
spec:
  build:
    env:
      - name: CGO_ENABLED
        value: "0"
    resources: {}
  builder:
    kind: ClusterBuilder
      name: my-builder
  cache:
    volume:
      size: 2G
  failedBuildHistoryLimit: 10
  imageTaggingStrategy: BuildNumber
  serviceAccountName: cartographer-example-registry-creds-sa
  source:
    blob:
      url: http://source-controller.gitops-toolkit.svc.cluster.local./gitrepository/default/hello/af9d9e843543fa20ac59019d20e685375c687093.tar.gz
  successBuildHistoryLimit: 10
  tag: 10.138.0.2:5000/example-basic-sc-hello
status:
  buildCacheName: hello-cache
  buildCounter: 1
  conditions:
    - lastTransitionTime: "2022-02-10T23:31:40Z"
      status: "True"
      type: Ready
    - lastTransitionTime: "2022-02-10T23:31:40Z"
      status: "True"
      type: BuilderReady
  latestBuildImageGeneration: 1
  latestBuildReason: CONFIG
  latestBuildRef: hello-build-1
  latestImage: 10.138.0.2:5000/example-basic-sc-hello@sha256:92b8a4c87145a939c431fd79a9ecd542af0b191cde4cbfd2480aaac7756a9db9
  latestStack: io.buildpacks.stacks.bionic
  observedGeneration: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      serviceAccountName: cartographer-example-registry-creds-sa
      containers:
        - name: hello
          image: 10.138.0.2:5000/example-basic-sc-hello@sha256:92b8a4c87145a939c431fd79a9ecd542af0b191cde4cbfd2480aaac7756a9db9
