apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hello
  labels:
    app.tanzu.vmware.com/workload-type: web
spec:
  build:
    env:
      - name: CGO_ENABLED
        value: "0"
  serviceAccountName: cartographer-example-basic-sc-sa
  source:
    git:
      ref:
        branch: main
      url: https://github.com/waciumawanjohi/demo-hello-world
